### ISSUE TITLE
cute_tiled animations not freed

### ISSUE THREAD

**Issue by aganm** [RandyGaul/cute_headers#271]
I found a memory leak happening here

https://github.com/RandyGaul/cute_headers/blob/3510be718b7657d41d05b6aa33b577e89ed13b30/cute_tiled.h#L2147

I think the respective free calls are missing

**Comment by RandyGaul** [comment]
Thanks for catching this!

**Comment by RandyGaul** [comment]
As far as I can see, it should be free'd here. Do you have a tiled file I can use for testing? https://github.com/RandyGaul/cute_headers/blob/master/cute_tiled.h#L2739

**Comment by RandyGaul** [comment]
My apologies for not being super on-top of this. It's a little time consuming for me to make my own test tiled files, as I no longer use Tiled for my own game. Though, I like Tiled and want to continue supporting cute_tiled :)

**Comment by aganm** [comment]
When using an embedded tileset there's no leak, only when I use an external tileset does valgrind give me a leak here:
```
Direct leak of 768 byte(s) in 3 object(s) allocated from:
    #0 0x7f90985047ef in __interceptor_malloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cpp:145
    #1 0x7f9097d19791 in cute_tiled_read_animation_frames_internal ../../lib/cute_headers/cute_tiled.h:2147
```

The way I'm loading/destroying my files is as such:
```
// Load
cute_tiled_map_t *map = cute_tiled_load_map_from_file("units32.json", NULL);
cute_tiled_tileset_t *tileset = map->tilesets;

cute_tiled_tileset_t *external = NULL;
if (tileset && tileset->source.ptr) { // if it has a source it means it's external
     external = cute_tiled_load_external_tileset(tileset->source.ptr, NULL);
}

// Destroy
if (external) {
    cute_tiled_free_external_tileset(external);
}
cute_tiled_free_map(map);
```

Here are the files to reproduce
[tiled.zip](https://github.com/RandyGaul/cute_headers/files/8127405/tiled.zip)

**Comment by RobLoach** [comment]
I'm don't believe this is an issue. The frames are read to the tile descriptor's `animation`...
```
cute_tiled_read_animation_frames(m, &tile_descriptor->animation, &tile_descriptor->frame_count);
```

In `cute_tiled_free_map_internal()`, the `desc->animation` is freed...
```
if (desc->animation) CUTE_TILED_FREE(desc->animation, mem_ctx);
```
